name: deepcad_web
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  # --- 核心 Python 和 Conda ---
  - python=3.9
  - pip

  # --- 机器学习和科学计算 ---
  - pytorch
  - torchvision
  - torchaudio
  - cudatoolkit=11.8  # !! 重要：请根据你的NVIDIA驱动版本调整 (例如 11.7, 12.1)
  - numpy
  - h5py
  - open3d

  # --- Django 后端 ---
  - django
  - djangorestframework
  - django-cors-headers
  - asgiref

  # --- 3D 可视化 (可选，但 show.py 需要) ---
#  - pythonocc-core=7.6.0  # 锁定一个已知稳定版本
  - pythonocc-core

  # --- 使用 pip 安装的包 ---
  # pointnet2_ops 需要手动编译安装，这里只是一个占位提醒
  - pip:
    - tqdm
    # - pointnet2_ops # <--- 这是一个提醒，你需要手动安装它